import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import joblib # Or import pickle if you used that

# -----------------------------------------------------------------------------
# Page Configuration
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Lending Rate Predictor",
    page_icon="💸",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -----------------------------------------------------------------------------
# Model & Feature Configuration
# -----------------------------------------------------------------------------

# --- 1. UPDATE THE MODEL PATH ---
MODEL_PATH = 'model.pkl' # IMPORTANT: Replace with the actual path to your model file

# --- 2. DEFINE FEATURE ORDER ---
# This list MUST be in the exact same order as the features your model was trained on.
# This is an EXAMPLE of what you will copy from your training script.
# Your actual list will be generated by the print command.

FEATURE_ORDER = [
    'month', 'repo_rate', 'gdp_growth', 'monthly_quarter', 
    'region_Maharashtra', 'bank_type_Public', 'loan_type_MSME', 
    'region_Delhi', 'bank_Kotak', 'season_Winter', 'region_Karnataka',
    'bank_Yes Bank', 'region_Tamil Nadu', 'loan_type_Agriculture',
    'region_Gujarat', 'bank_IndusInd', 'region_West Bengal', 'bank_Canara',
    'region_Haryana', 'region_Punjab', 'region_Andaman & Nicobar', 
    'region_Arunachal Pradesh', 'region_Assam', 'region_Bihar', 'region_Chandigarh',
    'region_Chhattisgarh', 'region_Dadra & Nagar Haveli', 'region_Goa',
    'region_Himachal Pradesh', 'region_Jammu & Kashmir', 'region_Kerala',
    'region_Ladakh', 'region_Madhya Pradesh', 'region_Meghalaya', 'region_Mizoram',
    'region_Rajasthan', 'region_Sikkim', 'region_Tripura', 'region_Uttarakhand',
    'bank_UCO Bank'
]

# --- 3. DEFINE USER-FRIENDLY OPTIONS FOR DROPDOWNS ---
REGION_OPTIONS = [
    'Andaman & Nicobar', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
    'Chhattisgarh', 'Dadra & Nagar Haveli', 'Delhi', 'Goa', 'Gujarat', 'Haryana',
    'Himachal Pradesh', 'Jammu & Kashmir', 'Karnataka', 'Kerala', 'Ladakh',
    'Madhya Pradesh', 'Maharashtra', 'Meghalaya', 'Mizoram', 'Punjab', 'Rajasthan',
    'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttarakhand', 'West Bengal'
]
BANK_OPTIONS = ['Canara', 'IndusInd', 'Kotak', 'UCO Bank', 'Yes Bank']
BANK_TYPE_OPTIONS = ['Public', 'Private']
LOAN_TYPE_OPTIONS = ['Agriculture', 'MSME']
SEASON_OPTIONS = ['Winter', 'Summer', 'Monsoon', 'Autumn'] # Assuming other seasons might be relevant

# -----------------------------------------------------------------------------
# Load Model
# -----------------------------------------------------------------------------

@st.cache_resource
def load_model(model_path):
    """Loads the pickled machine learning model with error handling."""
    try:
        with open(model_path, 'rb') as f:
            model = joblib.load(f)
        return model
    except FileNotFoundError:
        st.error(f"Model file not found at '{model_path}'. Please check the path.")
        return None
    except Exception as e:
        st.error(f"An error occurred while loading the model: {e}")
        return None

# Load the model
model = load_model(MODEL_PATH)

# -----------------------------------------------------------------------------
# Sidebar - User Inputs
# -----------------------------------------------------------------------------
st.sidebar.title("Prediction Inputs")
st.sidebar.markdown("Adjust the values to see the real-time prediction.")

# --- Input Groups ---
st.sidebar.header("Loan & Bank Details")
selected_region = st.sidebar.selectbox("Region", REGION_OPTIONS)
selected_bank = st.sidebar.selectbox("Bank", BANK_OPTIONS)
selected_bank_type = st.sidebar.selectbox("Bank Type", BANK_TYPE_OPTIONS)
selected_loan_type = st.sidebar.selectbox("Loan Type", LOAN_TYPE_OPTIONS)

st.sidebar.header("Time & Season")
selected_season = st.sidebar.selectbox("Season", SEASON_OPTIONS)
month_input = st.sidebar.slider("Month", 1, 12, 6)
monthly_quarter_input = st.sidebar.slider("Quarter", 1, 4, 2)

st.sidebar.header("Economic Factors")
repo_rate_input = st.sidebar.slider("Repo Rate (%)", 3.0, 9.0, 6.5, 0.25)
gdp_growth_input = st.sidebar.slider("GDP Growth (%)", -10.0, 10.0, 7.0, 0.1)


# -----------------------------------------------------------------------------
# Main Panel - Title, Prediction, and Visualizations
# -----------------------------------------------------------------------------
st.title("🏦 Comprehensive Lending Rate Predictor")
st.markdown("This dashboard uses a detailed model with 40 features for a nuanced prediction.")

if model:
    # --- Create the feature dictionary for the model ---
    input_features = {feature: 0 for feature in FEATURE_ORDER}

    # Set numerical features
    input_features['repo_rate'] = repo_rate_input
    input_features['gdp_growth'] = gdp_growth_input
    input_features['month'] = month_input
    input_features['monthly_quarter'] = monthly_quarter_input

    # Set one-hot encoded features based on user selection
    def set_one_hot(prefix, selection, features_dict):
        feature_name = f"{prefix}_{selection}"
        if feature_name in features_dict:
            features_dict[feature_name] = 1

    set_one_hot('region', selected_region, input_features)
    set_one_hot('bank', selected_bank, input_features)
    set_one_hot('loan_type', selected_loan_type, input_features)
    set_one_hot('season', selected_season, input_features)

    # Handle bank_type separately as it's 'Public' vs 'Private'
    if selected_bank_type == 'Public' and 'bank_type_Public' in input_features:
        input_features['bank_type_Public'] = 1

    # --- Prediction ---
    # Convert input dictionary to a DataFrame in the correct feature order
    input_df = pd.DataFrame([input_features])[FEATURE_ORDER]

    try:
        prediction = model.predict(input_df)[0]

        # --- Display Results ---
        st.markdown("---")
        st.header("Prediction Result")

        col1, col2 = st.columns([1, 2])

        with col1:
            st.metric(
                label="Predicted Lending Rate",
                value=f"{prediction:.2f}%",
                help="This is the lending rate predicted by the model based on the inputs from the sidebar."
            )

        with col2:
            # Create a gauge chart for visual context
            fig = go.Figure(go.Indicator(
                mode="gauge+number",
                value=prediction,
                title={'text': "Lending Rate Gauge"},
                gauge={'axis': {'range': [5, 15]}, # Adjust range as needed
                       'bar': {'color': "#2a9d8f"},
                       'steps': [
                           {'range': [5, 8], 'color': "#e9c46a"},
                           {'range': [8, 11], 'color': "#f4a261"},
                           {'range': [11, 15], 'color': "#e76f51"},
                       ]}
            ))
            fig.update_layout(height=250, margin=dict(l=10, r=10, t=50, b=10))
            st.plotly_chart(fig, use_container_width=True)

        # --- Model Transparency ---
        st.markdown("---")
        with st.expander("🔍 Click to see the feature vector used for this prediction"):
            st.dataframe(input_df)

    except Exception as e:
        st.error(f"An error occurred during prediction: {e}")

else:
    st.warning("Model is not loaded. Please check the configuration and file path.")
